### ISSUE TITLE
Decider install script is substandard

### ISSUE THREAD

**Issue by denis-yuen** [ICGC-TCGA-PanCancer/workflow-decider#3]
The decider install script needs to be re-written in ansible. This would allow us to run it idempotently when redeploying a machine. It has also been forked into a Ubuntu 12.04 and 14.04 script which is not maintainable and can be more simply expressed with Ansible's handling of different distribution types 
https://raymii.org/s/tutorials/Ansible_-_Only_if_on_specific_distribution_or_distribution_version.html

**Comment by adamjohnwright** [comment]
I created the Ansible playbook for instsalling bindle. Denis helped trouble shoot it and Solomon is going to change the architecure setup to point to this playbook instead of the old bash install scripts.
